### ISSUE TITLE
Measuring issue

### ISSUE THREAD

**Issue by abudriaz** [sorianog/indoor-nav-arcore#1]
been following this app on arms.com and youtube could not figure out how measuring and scaling unity map is done with respect to the real world  need an explaination on it please

**Comment by sorianog** [comment]
@abudriaz Please contact: https://community.arm.com/members/robertolopezmendez

**Comment by abudriaz** [comment]
@sorianog i have asked the question there got no reply can you explain how to do this?

**Comment by abudriaz** [comment]
i asked about the issue there no one is answering can you tell how you did
the scaling in navigation app!

**Comment by sorianog** [comment]
@abudriaz Asked the question on the post or did you contact the author directly? I want to know if you did the later as the author has more information than me. I don't own the demo and can't speak to its implementation.

**Comment by abudriaz** [comment]
have asked directly to the honor aswell no one responding :/
