### ISSUE TITLE
Acessibilty error

### ISSUE THREAD

**Issue by jeevanmali1994** [sorianog/indoor-nav-arcore#2]
Assets\GoogleARCore\SDK\Scripts\Managers\SessionManager.cs(79,34): error CS0053: Inconsistent accessibility: property type 'PointCloudManager' is less accessible than property 'SessionManager.PointCloudManager'

the unity studio gives this error. Tried everything but didnt get positive results

**Comment by sorianog** [comment]
Honestly, it has been a while since I launched this project back up again. I wonder if some frameworks need updating and code refactoring has to be done...🤔

**Comment by jeevanmali1994** [comment]
I got the error solved. This is due to temp files and setting files. We just need to delete the temp,project settings and library folders and reopen the scene. I read this solution somewhere and tried it.It worked. Thanks for Prompt reply.
Also "TrackableHitFlag" has to be changed to "TrackableHitFlags"

**Comment by sorianog** [comment]
@jeevanmali1994 Thank you so much for the information! I wonder if those files can be specified in the `.gitignore`
Feel free to open up a PR!

**Comment by jeevanmali1994** [comment]
I am new to github so dont know how to use .gitignore file.
The folders we should delete are Library,ProjectSettings and Temp

**Comment by sorianog** [comment]
All good. I'll see what I can do!

**Comment by jeevanmali1994** [comment]
Thanks. I have added a Pull request for another issue . The constant was changed in new ARCore library . Have a look at that
